on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:uno"
          libraries: |
            - name: ADS1119
