name: test

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["arduino:samd", "arduino:avr", "esp32:esp32"]
        include:
          - arduino-platform: "arduino:samd"
            fqbn: "arduino:samd:nano_33_iot"
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32-poe-iso"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Setup Arduino CLI
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
            tools: arduino-cli
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
      - name: Compile Sketch ADS1119-basic      
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} --libraries=./ ./examples/ADS1119-basic
      - name: Compile Sketch ADS1119-advanced
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} --libraries=./ ./examples/ADS1119-advanced